### ISSUE TITLE
Features for version 1.1

### ISSUE THREAD

**Issue by grimsi** [grimsi/gamelinker#1]
- [x] Merge all scripts into one by using the ~~[gmod_luasocket](https://github.com/danielga/gmod_luasocket)~~ [gm_bromsock](https://github.com/Bromvlieg/gm_bromsock) library.
- [x] Config file in JSON
- [x] Implement Asynchronous Callbacks

This will make the complicated installation process obsolete and will allow the script to run 24/7 directly on the gameserver without supervision.

**Comment by TheRapie** [comment]
This error occurs after running ts-script.exe

[ts-script.exe:42 (a nil value)](http://i65.tinypic.com/2ihnqzs.png)

Luaforwinows is installed,
start as admin does not fix it
changing folder which contains .exe does not work

**Comment by grimsi** [comment]
Version 1.1 in now in beta!
Send me an E-Mail (webmaster@grimsi.de) or add me on [Steam](http://steamcommunity.com/id/Cr4zyPi3t) to get beta access!
