### ISSUE TITLE
ts-script.exe Error

### ISSUE THREAD

**Issue by TheRapie** [grimsi/gamelinker#2]
This error occurs after running ts-script.exe

[ts-script.exe:42 (a nil value)](http://i65.tinypic.com/2ihnqzs.png)

LuaForWindows is installed,
start as admin does not fix it
changing folder which contains .exe does not work

**Comment by grimsi** [comment]
This error occurs when you dont edit the file paths in "config.txt" to match the paths on your computer.

**Comment by TheRapie** [comment]
i did edit the path, maybe i did something wrong syntax wise?

here is my confix.txt line

Path to data Folder:d:\\\Spiele\\\Steamcmd\\\steamcmd\\\steamapps\\\common\\\GarrysModDS\\\garrysmod\\\data;

**Comment by grimsi** [comment]
d:\\\Spiele\\\Steamcmd\\\steamcmd\\\steamapps\\\common\\\GarrysModDS\\\garrysmod\\\data
You have to escape the "\\" with another "\\"

**Comment by TheRapie** [comment]
i am not even using ""? am i missing something?

**Comment by TheRapie** [comment]
i did, but git commented it out. i did double backslash. the error still occurs. i even double checked the path and the formatting jsut now

**Comment by grimsi** [comment]
Yup, I noticed it when writing my comment. Contact me on Steam so we can figure this out: http://steamcommunity.com/id/Cr4zyPi3t

**Comment by grimsi** [comment]
*Closed*
Scripts werent installed correctly and server query didnt have sufficient permission
