### ISSUE TITLE
Couldn't include file 'includes/modules/bromsock.lua' (File not found) 

### ISSUE THREAD

**Issue by enyineer** [grimsi/gamelinker#5]
The bromsock.lua file (getting loaded in the script at line one) doesn't exist in a vanilla Garrys Mod Server. It also isn't included in this git.

**Comment by Bobert42** [comment]
have you moved "gmsv_bromsock_win32.dll" or "gmsv_bromsock_linux.dll" (depending on what distribution your server runs) into the right folder?

**Comment by grimsi** [comment]
You do Not need a bromsock.lua File.You need the bromsock.dll File from the gitAm 27.05.2017 22:57 schrieb Nico Enking <notifications@github.com>:The bromsock.lua file (getting loaded in the script at line one) doesn't exist in a vanilla Garrys Mod Server. It also isn't included in this git.

**Comment by enyineer** [comment]
I did everything like the tutorial told me. The error still occurs and the plugin doesnt work. It is looking for a bromsock.lua in the includes folder. I even tryed redownloading the dll for windows of the original authors git, but this didnt work either.

**Comment by enyineer** [comment]
PS: I can provide you screenshots of the error message tomorrow (it's late here in Germany, I wanted to go to bed now).

**Comment by grimsi** [comment]
It would be great if you could provide some Screenshots from the error Message and your folder structure.

**Comment by enyineer** [comment]
![error](https://cloud.githubusercontent.com/assets/27201677/26527786/8f4676fa-439b-11e7-9815-c421de5f1269.png)
![folder1](https://cloud.githubusercontent.com/assets/27201677/26527788/8f479ec2-439b-11e7-85fa-6372537267da.png)
![folder2](https://cloud.githubusercontent.com/assets/27201677/26527789/8f47b682-439b-11e7-85fd-2e27fba21c68.png)
![notfound](https://cloud.githubusercontent.com/assets/27201677/26527787/8f4787fc-439b-11e7-89e5-12b3d2e66467.png)

The error is now different than it was yesterday (I dont know why, but there is still an error)

Edit: I'm running this on a windows server 2k8 R2 machine.

**Comment by grimsi** [comment]
Thanks for the screenshots.
Its okay that there is no "bromsock.lua" in the modules folder, since you dont need it.
But I see that youre running a pretty old Windows version (or at least enabled the classic look).
The script is tested for Windows 7 and above, so I cant guarantee that it will work with Windows 2000, XP or Vista.
Edit: Windows Server 2008 should be able to run the script. Im on a business trip next week so I will have a look at it on Friday.

**Comment by enyineer** [comment]
Hey Grimsi, thanks for the answer. This is a Windows Server 2k8 R2 machine (equals Windows 7) so this should work.

**Comment by grimsi** [comment]
Yeah sorry, I didnt read your edit at first.
Is your Maschine 32 or 64 Bit?

**Comment by enyineer** [comment]
It is a 64 bit machine.

**Comment by grimsi** [comment]
Did you try both versions of the .DLL (32 and 64 Bit)?

**Comment by enyineer** [comment]
I only found a win32 dll. Where can I get the 64 bit one?

**Comment by Bobert42** [comment]
Since Garry's Mod is a pure 32bit application I don't think that a 64bit dll will work at all (and I don't think there is one either).

Did you allready try recompiling the _"gmsv_bromsock_win32.dll"_ from source ( [gm_bromsock source](https://github.com/Bromvlieg/gm_bromsock) )?
