### ISSUE TITLE
[TS-Automute] Connection to TeamSpeak could not be established!

### ISSUE THREAD

**Issue by SireKuja** [grimsi/gamelinker#6]
Heya,
I have a problem establishing your TTT-Mutebot.
I'm able to connect via telnet to my TeamSpeak server, but when im trying to start my server there is a message that says "[TS-Automute] Connection to TeamSpeak could not be established!" in errorlog.

**Comment by SireKuja** [comment]
I fixed it by myself, the problem was that my external TeamSpeak Server wasn't supportingTCP-Sockets.

**Comment by grimsi** [comment]
Sorry, I was at work and didnt have time to answer, but im glad you resolved this issue yourself.
