### ISSUE TITLE
Players dying in Warmup cant speak in the round

### ISSUE THREAD

**Issue by WookieFPV** [grimsi/gamelinker#7]
If someone dies before the round start, they will be muted and not be unmuted if the round beginns.
They will respawn after the warmup but are still muted because they died.

**Comment by Bobert42** [comment]
#9 hopefully this should fix this.

**Comment by WookieFPV** [comment]
after looking in the garrys mod documentation I came up with the exact same solution.
I hope this event is triggered even at respawn by Items like secound chance

**Comment by grimsi** [comment]
Thanks for fixing :)
